### PR TITLE
updating valast to fix type misalignment in code generation

### PR DESCRIPTION
**Pull request by fkautz**
Signed-off-by: Frederick F. Kautz IV <fkautz@alumni.cmu.edu>

### CODE REVIEW

**Comment by fkautz** [comment]
Converted to draft to work on upstreaming valast changes.

**Review by kris-nova — APPROVED** [review]

**Comment by kris-nova** [comment]
Any update on this?

**Comment by fkautz** [comment]
I needed a break to recover from burn out. :x 

I'll get back on this shortly.

**Comment by kris-nova** [comment]
closed with #95

**Pull request closed without merging**
